profile-name: "test"

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/petkpetk
    username: rene
    password: itiswhatitis
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

  sql:
    init:
      mode: always

#    "spring.jpa.hibernate.ddl-auto=none",
#    "spring.datasource.url=jdbc:h2:mem:testdb",
#    "spring.datasource.username=sa",
#    "spring.datasource.password=",
#    "spring.datasource.driver-class-name=org.h2.Driver"